spring:
  application:
    name: gatewayserver
  main:
    banner-mode: off
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: admission-advisor-service
              uri: lb://ADMISSION-ADVISOR-SERVICE
              predicates:
                - Path=/admission/**
              filters:
                - StripPrefix=1
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
            - id: school-service
              uri: lb://SCHOOL-SERVICE
              predicates:
                - Path=/school/**
              filters:
                - StripPrefix=1
            - id: forum-service
              uri: lb://FORUM-SERVICE
              predicates:
                - Path=/forum/**
              filters:
                - StripPrefix=1

logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace

server:
  port: 8800

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
