server:
  port: 8000
spring:
  application:
    name: admission-advisor-service
  datasource:
    url: jdbc:postgresql://localhost:5432/admission_advisor_service_db
    username: postgres
    password: 12345
  main:
    banner-mode: off
    lazy-initialization: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=
    key: AIzaSyBXWR8BHNoMmA_T0mjHT1T6P_Q06NlGCQ0