server:
  port: 8002
spring:
  application:
    name: school-service
  datasource:
    url: jdbc:postgresql://localhost:5432/school_service_db
    username: postgres
    password: 12345
  main:
    banner-mode: off
    lazy-initialization: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api
  show-actuator: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/