server:
  port: 8005
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: postgres
    password: 12345
  main:
    banner-mode: off
    lazy-initialization: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-kakan-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    org.springframework.kafka.listener: DEBUG
    org.apache.kafka.clients.consumer: TRACE
    root: warn
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/