server:
  port: 8004
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres:5432/order_service_db
    username: postgres
    password: 12345
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: orders-kakan-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:8070/eureka/