server:
  port: 8004
spring:
  application:
    name: admission-advisor-service
  datasource:
    url: jdbc:postgresql://postgres:5432/order_service_db
    username: postgres
    password: 12345
  main:
    banner-mode: off
    lazy-initialization: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always


springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:8070/eureka/