DROP TABLE IF EXISTS "order" CASCADE;

CREATE TABLE "order" (
    order_id SERIAL PRIMARY KEY,
    account_id INTEGER NOT NULL,
    price DECIMAL(12,2) NOT NULL CHECK (price >= 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','EXPIRED','SUCCESS')),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    order_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expired_date TIMESTAMP WITH TIME ZONE
);
