name: Deploy Microservices with Docker Compose

on:
  push:
    branches: [ "release" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Generate UUID as version tag
        id: uuid
        run: echo "TAG=$(uuidgen)" >> $GITHUB_ENV

      - name: Replace :latest with UUID tag in build file
        run: sed -i "s/:latest/:$TAG/g" docker-compose.yml

      - name: Build all images using Docker Compose
        run: docker compose -f docker-compose.yml build

      - name: Push all images using Docker Compose
        run: docker compose -f docker-compose.yml push

      - name: Replace :latest with UUID tag in deploy file
        run: sed -i "s/:latest/:$TAG/g" docker-compose.yml

      - name: Upload deploy docker-compose.yml to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: kakan
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.deploy.yml"
          target: "/home/kakan/microservices"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: kakan
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/kakan/microservices
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d --remove-orphans
