name: Deploy Microservices with Docker Compose

on:
  push:
    branches: [ "release" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Generate UUID as version tag
        id: uuid
        run: echo "TAG=$(uuidgen)" >> $GITHUB_ENV

      - name: Build and push Docker images
        run: |
          services=(
            eureka
            gatewayserver
            admission-advisor-service
            forum-service
            school-service
            user-service
            order-service
            payment-service
          )

          for service in "${services[@]}"; do
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$service:$TAG -f $service/Dockerfile .
            docker push ${{ secrets.DOCKER_USERNAME }}/$service:$TAG
          done

      - name: Upload docker-compose.yml to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: kakan
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/kakan/microservices"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: kakan
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/kakan/microservices
            sed -i "s/:latest/:$TAG/g" docker-compose.yml
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans
